[package]
name = "confcosmos"
description = "A TUI tool for quickly creating symlinks, Linux only"
author = "yak93rise"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
toml = "0.8"
toml_edit = "0.22"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
